baseurl = "https://blog.vlgdata.io"
DefaultContentLanguage = "en"
date = "2020-04-26T13:41:21+02:00"
title = "VLG Data"
theme = "beautifulhugo"
metaDataFormat = "yaml"
googleAnalytics = "UA-165238354-1"

#disqusShortname = "XXX"

#pygmentsStyle = "colorful"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
#pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "pygments"
    tabWidth = 4

[Params]
  homeTitle = "VLG Data Engineering"
  subtitle = "A blog on Data Engineering & Machine Learning Operations"
  mainSections = ["post","posts"]
  logo = "img/profile/p3.jpeg" # Expecting square dimensions
  favicon = "img/icon/settings.png"
  #favicon = "img/icon/gear_32.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = false
  wordCount = false
  useHLJS = false
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true
  #gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
  custom_css = ["css/custom.css"]


#[[Params.bigimg]]
    #src = "img/triangle.jpg"
    #desc = "Triangle"
#[[Params.bigimg]]
    #src = "img/sphere.jpg"
    #desc = "Sphere"
    #position: see values of CSS background-position.
    #position = "center top"
#[[Params.bigimg]]
#    src = "img/hexagon.jpg"
#    desc = "Hexagon"

[Author]
  name = "Vincent Le Goualher"
  website = "blog.vlgdata.io"
  email = "vlg.engineer@gmail.com"
  #facebook = "username"
  github = "datatrigger"
  #gitlab = "datatrigger"
  #bitbucket = "username"
  #twitter = "vincentgoualher"
  #reddit = "username"
  linkedin = "vlgdata"
  #xing = "username"
  #stackoverflow = "users/13450581/vincent-le-goualher"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2


